#!/usr/bin/env bash
# Shared helpers for the evidence-based verification scripts.
# Source this from scripts/*.sh:  source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE_DIR="${REPO_ROOT}/evidence/latest"
CONFIG_LOCAL="${REPO_ROOT}/config/hardware.local.yaml"
CONFIG_EXAMPLE="${REPO_ROOT}/config/hardware.example.yaml"

mkdir -p "${EVIDENCE_DIR}"

timestamp_utc() {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# reset_evidence_dir
# Removes only files generated by the fixed verification entry points. This
# prevents stale results from being mixed into a new verification summary while
# leaving any unrelated operator-collected files in evidence/latest alone.
reset_evidence_dir() {
    local generated_files=(
        build.log
        build_result.json
        flash.log
        flash_result.json
        hil.log
        hil_result.json
        uart.log
        uart_result.json
        gdb_snapshot.log
        gdb_snapshot.json
        logic_i2c_decode.txt
        logic_i2c_result.json
        verification.md
    )

    local f
    for f in "${generated_files[@]}"; do
        rm -f "${EVIDENCE_DIR}/${f}"
    done
}

# cfg_get <dot.separated.key> [default]
# Reads config/hardware.local.yaml if present, else config/hardware.example.yaml.
# Values like "${PICO_UART_PORT}" are expanded from the environment; if the
# variable is unset the default is returned, so nothing local ever gets baked in.
cfg_get() {
    python3 - "$1" "${2:-}" "${CONFIG_LOCAL}" "${CONFIG_EXAMPLE}" <<'PYEOF'
import os, sys

key, default, local_path, example_path = sys.argv[1:5]
path = local_path if os.path.exists(local_path) else example_path

value = None
try:
    import yaml
    with open(path) as f:
        node = yaml.safe_load(f) or {}
    for part in key.split("."):
        node = node[part]
    value = node
except Exception:
    value = None

if value is None:
    print(default)
    sys.exit(0)

expanded = os.path.expandvars(str(value))
# Unresolved ${VAR} means the env var is not set locally -> fall back.
print(default if "${" in expanded else expanded)
PYEOF
}

# hardware_gate <step> <result_json_path> <log_path>
# Safety gate: hardware-touching steps run only when PICO_HARDWARE=1 is set
# explicitly. Otherwise writes a skip result and exits 0. AI agents must not
# work around this gate (see docs/operations/AGENT_OPERATION.md).
hardware_gate() {
    if [ "${PICO_HARDWARE:-0}" != "1" ]; then
        local reason="hardware not enabled. Set PICO_HARDWARE=1 to enable hardware operations."
        echo "SKIP: ${reason}" | tee "$3"
        write_result_json "$2" "$1" "skip" "${reason}" "evidence/latest/$(basename "$3")"
        exit 0
    fi
}

# write_result_json <outfile> <step> <status> [reason] [log_relpath]
# status: pass | fail | skip | stub
write_result_json() {
    python3 - "$@" <<'PYEOF'
import json, sys
from datetime import datetime, timezone

argv = sys.argv[1:]
out, step, status = argv[0], argv[1], argv[2]
result = {
    "step": step,
    "status": status,
    "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
}
if len(argv) > 3 and argv[3]:
    result["reason"] = argv[3]
if len(argv) > 4 and argv[4]:
    result["log"] = argv[4]
with open(out, "w") as f:
    json.dump(result, f, indent=2)
    f.write("\n")
PYEOF
}
