#!/usr/bin/env python3
"""Generate evidence/latest/verification.md from the evidence files.

Reads the *_result.json / gdb_snapshot.json files written by the scripts/
entry points and produces a single Markdown summary that both humans and AI
agents can read to judge what passed, what failed, and what was never run.

This script never guesses: a step with no result file is reported as
"not run", and stub/skip results are labeled as such.

Usage: python3 scripts/summarize_evidence.py
Exit code: 0 unless verification.md could not be written.
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVIDENCE_DIR = REPO_ROOT / "evidence" / "latest"

# (step label, result json filename, associated log/evidence filenames)
STEPS = [
    ("Build", "build_result.json", ["build.log"]),
    ("Flash", "flash_result.json", ["flash.log"]),
    ("HIL", "hil_result.json", ["hil.log"]),
    ("UART", "uart_result.json", ["uart.log"]),
    ("GDB", "gdb_snapshot.json", []),
    ("Logic Analyzer", "logic_i2c_result.json", ["logic_i2c_decode.txt"]),
]


def load_result(filename):
    path = EVIDENCE_DIR / filename
    if not path.exists():
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        return {"status": "error", "reason": f"unreadable result file: {e}"}


def overall_status(statuses):
    """fail > partial > pass > skipped, based on per-step statuses."""
    real = [s for s in statuses if s is not None]
    if not real:
        return "skipped"
    if "fail" in real or "error" in real:
        return "fail"
    if "pass" in real and all(s == "pass" for s in real) and None not in statuses:
        return "pass"
    if "pass" in real:
        return "partial"
    return "skipped"


def main():
    results = {label: load_result(fname) for label, fname, _ in STEPS}
    statuses = [r["status"] if r else None for r in results.values()]

    lines = []
    lines.append("# Verification Summary")
    lines.append("")
    lines.append(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} (UTC)")
    lines.append("")
    lines.append("## Overall Status")
    lines.append("")
    lines.append(f"**{overall_status(statuses)}**")
    lines.append("")

    lines.append("## Evidence Files")
    lines.append("")
    for label, fname, logs in STEPS:
        for f in [fname] + logs:
            path = EVIDENCE_DIR / f
            mark = "present" if path.exists() else "missing"
            lines.append(f"- `{f}` ({mark})")
    lines.append("")

    lines.append("## Results")
    lines.append("")
    for label, fname, _ in STEPS:
        r = results[label]
        if r is None:
            lines.append(f"- {label}: not run (no `{fname}`)")
            continue
        entry = f"- {label}: {r.get('status', 'unknown')}"
        if r.get("reason"):
            entry += f" — {r['reason']}"
        lines.append(entry)
    lines.append("")

    lines.append("## Notes")
    lines.append("")
    notes = []
    for label, fname, _ in STEPS:
        r = results[label]
        if r is None:
            notes.append(f"- {label}: 未実施。証拠ファイル `{fname}` がありません。")
        elif r.get("status") == "skip":
            notes.append(f"- {label}: スキップ ({r.get('reason', '理由不明')})。実機未接続または未設定です。")
        elif r.get("status") == "stub":
            notes.append(f"- {label}: スタブ結果です。実測値ではありません ({r.get('reason', '')})。")
        elif r.get("status") == "error":
            notes.append(f"- {label}: 結果ファイルが壊れています ({r.get('reason', '')})。")
    if not notes:
        notes.append("- 全ステップが実測結果に基づいています。")
    lines.extend(notes)
    lines.append("")
    lines.append("---")
    lines.append("Generated by `scripts/summarize_evidence.py`. "
                 "Judgments must be based on the evidence files above, "
                 "not on this summary alone (see docs/TEST_EVIDENCE_POLICY.md).")
    lines.append("")

    out = EVIDENCE_DIR / "verification.md"
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Wrote {out.relative_to(REPO_ROOT)}")
    print(f"Overall status: {overall_status(statuses)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
